### ISSUE TITLE
examples/udp is using NuttX's CONFIG_ENDIAN_BIG for host OS program

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx-apps#157]
the same issue as https://github.com/apache/incubator-nuttx-apps/issues/150

**Comment by xiaoxiang781216** [comment]
Fixed by #156, let's close this issue now.

**Comment by yamt** [comment]
no, https://github.com/apache/incubator-nuttx-apps/pull/156 doesn't fix this.
